import "server-only";

import data from "@/data/catalog.json";
import {
  CATEGORY_TREE,
  PRACTICE,
  type CategoryNode,
  type CountedNode,
} from "./categories";
import type { ProblemRow } from "./problem";

// Generated by scripts/extract-problems.mjs: every problem is stored once and
// categories reference it by index. Only server code imports this, and every
// route is prerendered, so it never reaches the client or runs per request.
const catalog = data as unknown as {
  problems: ProblemRow[];
  categories: Record<string, number[]>;
};

export function getProblems(slug: string): ProblemRow[] | undefined {
  return catalog.categories[slug]?.map((i) => catalog.problems[i]);
}

export function getCount(slug: string): number {
  return catalog.categories[slug]?.length ?? 0;
}

function difficulties(slug: string): number[] {
  return (catalog.categories[slug] ?? []).map((i) => catalog.problems[i][4]);
}

export function getMedianDifficulty(slug: string): number {
  const sorted = difficulties(slug).sort((a, b) => a - b);
  return sorted.length ? sorted[sorted.length >> 1] : 0;
}

/** Slugs of every category that has both a known title and problem data. */
export function getCategorySlugs(): string[] {
  const slugs: string[] = [];
  const walk = (nodes: CategoryNode[]) => {
    for (const node of nodes) {
      if (getCount(node.slug) > 0) slugs.push(node.slug);
      if (node.children) walk(node.children);
    }
  };
  walk([PRACTICE, ...CATEGORY_TREE]);
  return slugs;
}

export function getCountedTree(): CountedNode[] {
  const count = (node: CategoryNode): CountedNode[] => {
    const total = getCount(node.slug);
    if (total === 0) return [];
    return [
      {
        slug: node.slug,
        title: node.title,
        count: total,
        children: (node.children ?? []).flatMap(count),
      },
    ];
  };
  return CATEGORY_TREE.flatMap(count);
}

export function getUniqueProblemCount(): number {
  return catalog.problems.length;
}
